const {app,BrowserWindow}=require('electron');const path=require('node:path');const fs=require('node:fs/promises');
require(process.argv.includes('--packaged')?'../release/win-unpacked/resources/app.asar/electron/main.cjs':'../electron/main.cjs');app.setPath('userData',path.join(__dirname,'../.smoke-data/journal-'+Date.now()));
app.whenReady().then(async()=>{try{const win=BrowserWindow.getAllWindows()[0];if(win.webContents.isLoading())await new Promise(r=>win.webContents.once('did-finish-load',r));const result=await win.webContents.executeJavaScript(`(async()=>{
const wait=()=>new Promise(r=>setTimeout(r,300));await wait();const click=text=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim().includes(text));if(!b)throw Error('Missing '+text);b.click();};const change=(selector,value,type='change')=>{const el=document.querySelector(selector);el.value=value;el.dispatchEvent(new Event(type,{bubbles:true}));};
click('Forge a character');await wait();click('Save');await wait();const journal=document.querySelector('.run-tracking');if(journal.querySelector('button'))throw Error('Buttons remain in journal');if(journal.querySelector('input[type=checkbox]'))throw Error('Completion checkboxes remain');if(journal.querySelector('h2').textContent!=='Journal')throw Error('Wrong heading');
const [a,b]=journal.querySelectorAll('.facts>div');if(Math.abs(a.getBoundingClientRect().width-b.getBoundingClientRect().width)>1)throw Error('Status fields differ in width');for(const label of journal.querySelectorAll('label'))if(getComputedStyle(label).textAlign!=='center')throw Error('Label not centered');if(document.querySelector('#run-notes').getBoundingClientRect().height<300)throw Error('Journal too short');
change('#run-notes','A','input');await wait();let data=await window.ledger.load();if(data.characters[0].notes!=='A')throw Error('First keystroke not saved');
for(let i=0;i<15;i++)change('#run-notes','A journal entry '+i,'input');change('#run-hours','12.5','input');await wait();data=await window.ledger.load();const c=data.characters[0];if(c.notes!=='A journal entry 14'||c.hours!==12.5)throw Error('Rapid autosaves lost data');
for(const id of ['#main-progression','#side-progression']){const select=document.querySelector(id);change(id,select.options[select.options.length-1].value);await wait();}data=await window.ledger.load();if(!data.characters[0].mainComplete||!data.characters[0].sideComplete||document.querySelectorAll('.completion-indicator.complete').length!==2)throw Error('Completion not derived');
const main=document.querySelector('#main-progression');change('#main-progression',main.options[1].value);await wait();data=await window.ledger.load();if(data.characters[0].mainComplete)throw Error('Completion not cleared');
change('#run-status','Dead');await wait();change('#death-cause','Clannfear','input');change('#run-notes','Final words','input');await wait();data=await window.ledger.load();if(data.characters.filter(c=>c.status==='Dead').length!==1||data.characters[0].killedBy!=='Clannfear')throw Error('Death autosave failed');
return {id:c.id};})()`);
const reloaded=new Promise(r=>win.webContents.once('did-finish-load',r));win.reload();await reloaded;await win.webContents.executeJavaScript(`(async()=>{const wait=()=>new Promise(r=>setTimeout(r,300));await wait();const click=text=>[...document.querySelectorAll('button')].find(x=>x.textContent.trim().includes(text)).click();click('Characters');await wait();document.querySelector('.card-select').click();await wait();if(document.querySelector('#run-notes').value!=='Final words')throw Error('Journal lost after reload');document.querySelector('.trash-button').click();await wait();if(!document.querySelector('.delete-dialog[open]'))throw Error('Delete popup missing');click('Yes');await wait();const d=await window.ledger.load();if(d.characters.length)throw Error('Delete/history failed');})()`);console.log('Journal autosave, rapid typing, reload, completion, death and card deletion passed');app.exit();}catch(e){console.error(e);app.exit(1);}});


