import {Component,signal,ViewChild,ElementRef} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {FormsModule} from '@angular/forms';
import {NgTemplateOutlet} from '@angular/common';
import {Character,Ledger,generate,races,birthsigns,attributes,skills,quests} from './model';
import {portraitArmor,portraitKey,portraitSource} from './portraits';
import {FitNameDirective} from './fit-name.directive';
import {PortraitComponent} from './portrait.component';
import {NAME_LIMIT,limitName} from './names';
import {SheetHeightDirective} from './sheet-height.directive';
import {questlines,questStages,questPercent,deriveCompletion,migrateProgress} from './questlines';
import {deathCount,migrateChallenge} from './challenge';
declare global {interface Window {ledger?:{load():Promise<Ledger>;save(d:Ledger):Promise<void>;path():Promise<string>;export():Promise<boolean>;onFlush?(callback:()=>Promise<void>):void}}}
@Component({selector:'app-root',standalone:true,imports:[FormsModule,NgTemplateOutlet,SheetHeightDirective,PortraitComponent,FitNameDirective],template:`
<ng-template #characterSheet let-c><div class="name-row"><input #characterName class="name" fitName [attr.maxlength]="nameLimit" aria-label="Character name" title="Edit character name (up to 24 characters)" [ngModel]="c.name" (ngModelChange)="c.name=limitName($event); nameChanged(c)"><button class="name-edit" aria-label="Edit character name" title="Edit character name" (click)="characterName.focus(); characterName.select()">✎</button></div><div class="sheet-meta">{{c.mode}}{{c.challenge?' · Challenge':''}}</div>
<section class="sheet-section"><h2>Race</h2><p class="race-value">{{c.race}} <span class="subrace">{{c.origin}}</span></p></section>
<section class="sheet-section"><h2>Birthsign</h2><p>The {{c.birthsign}}</p></section>
<section class="sheet-section class-section"><h2>Class</h2><div class="class-field"><h3>Specialization</h3><p>{{c.specialization}}</p></div><div class="class-field"><h3>Favored Attributes</h3><div class="attribute-columns">@for(a of sorted(c.attributes);track a){<span>{{a}}</span>}</div></div><div class="class-field"><h3>Favored Skills</h3><div class="skill-columns">@for(column of skillColumns(c);track $index){<ul>@for(s of column;track s){<li>{{s}}</li>}</ul>}</div></div></section>
<section class="sheet-section objectives-section"><h2>Objectives</h2><ul><li>Main Quest</li><li>{{c.quest}}</li></ul></section></ng-template>
<div class="shell"><aside><img class="app-logo" src="assets/Fantasy Adventurer Crest Medallion.png" alt="Oblivion Remastered: Random Character Generator crest"><div class="brand">OBLIVION<span class="remastered">REMASTERED</span><span>Random Character<br>Generator</span></div><div class="rule"></div><nav>@for(t of tabs;track t){<button [class.active]="tab()===t" (click)="tab.set(t)">{{t==='Forge'?'✦':t==='Characters'?'▤':'◇'}} <span>{{t}}</span>@if(t==='Characters'){<small>{{data.characters.length}}</small>}</button>}</nav><div class="aside-bottom">Every life tells a story.<br>Let chance write yours.<div class="rule"></div><small>OBLIVION REMASTERED</small></div></aside>
<main><header><span>THE ELDER SCROLLS IV</span><span class="local">● {{ready()?'LOCAL SAVE':'LOADING'}} · v2.0.0</span></header>
@if(error()){<div class="error" role="alert">{{error()}}</div>}
@if(tab()==='Forge'){
<div class="eyebrow">A NEW BEGINNING</div><h1>Leave your fate to chance.</h1><p class="intro">A stranger, a constellation, a calling. Your next journey through Cyrodiil starts here.</p>
<div class="forge-layout"><section class="panel settings"><div class="section-title"><h2>Choose Your Fate</h2></div><label class="settings-heading">Randomization Options</label>@for(m of modes;track m){<button class="mode" [class.selected]="mode===m" (click)="mode=m"><strong>{{m}}</strong><span>{{m==='Balanced Random'?'At least one skill that can do damage, no more than one melee skill, and no more than one armor type. (Recommended)':'Unfiltered chance. Embrace the unexpected.'}}</span></button>}
<div class="rule"></div><label class="settings-heading">Challenge Mode</label><label class="toggle"><input type="checkbox" [(ngModel)]="challenge"> Permadeath Challenge</label>
<p class="challenge-deaths">Number of Dead Characters: {{deaths()}}</p><p class="hint">Each dead character you don't delete provides one stat change during character creation to anything you want it to be.</p>
<button class="primary" (click)="roll()" [disabled]="!ready()">✦ &nbsp; Forge a character</button></section>
<div class="character-preview" [class.has-character]="!!draft()" matchPortraitHeight><section class="panel sheet">@if(draft();as c){<div class="sheet-content"><ng-container [ngTemplateOutlet]="characterSheet" [ngTemplateOutletContext]="{$implicit:c}"></ng-container>
@if(c.challenge){<p class="hint">{{c.allowance-c.changes}} of {{c.allowance}} death-earned changes remaining. Changes are available before the run starts.</p>@if(c.changes<c.allowance){<div class="edit-row"><select [(ngModel)]="editField" (ngModelChange)="editValue=''">@for(f of changeFields(c);track f.value){<option [value]="f.value">{{f.label}}</option>}</select><select [(ngModel)]="editValue"><option value="">Choose replacement</option>@for(v of editOptions(c);track v){<option [value]="v">{{v}}</option>}</select><button (click)="change(c)" [disabled]="!editValue">Apply</button></div>}}
<div class="actions sheet-actions"><button (click)="roll()">Reroll</button><button class="primary" (click)="saveDraft()" [disabled]="busy()">Save</button></div></div>
} @else {<div class="empty"><div class="constellation">✧<br> · &nbsp; ◈ &nbsp; · <br>✦</div><h2>An unwritten story.</h2><p>Forge a character to reveal<br>who you’ll become.</p><small>10 RACES · 13 SIGNS · LIMITLESS STORIES</small></div>}</section>@if(draft();as c){<div class="portrait-panel"><app-portrait [character]="c" (variantChange)="portraitChanged(c,$event)"></app-portrait></div>}</div></div>
}
@if(tab()==='Characters'){
<div class="eyebrow">THE STORIES SO FAR</div><h1>Your characters.</h1><div class="list-tools"><input placeholder="Search name, race, or questline" aria-label="Search characters" [(ngModel)]="search"><select aria-label="Filter status" [(ngModel)]="filter"><option>All</option><option>Alive</option><option>Dead</option><option>Won</option></select><button (click)="backup()">Export JSON Backup</button><div class="save-info" (keydown.escape)="showSavePath.set(false)"><button class="info-button" aria-label="Save file location" title="Save file location" aria-controls="save-location" [attr.aria-expanded]="showSavePath()" (click)="showSavePath.set(!showSavePath())">ⓘ</button>@if(showSavePath()){<div id="save-location" class="save-location" role="note">Save file: {{savePath}}</div>}</div></div>
<div class="character-layout"><section class="character-list">@for(c of filtered();track c.id){<article class="character-card" [class.selected]="selected()?.id===c.id"><button class="card-select" (click)="select(c)"><h2>{{c.name}}</h2><p class="card-identity"><span>{{c.race}}</span><span>· The {{c.birthsign}}</span><span class="badge" [class.dead]="c.status==='Dead'">{{c.status}}</span></p><small class="card-progress"><span>Main Quest · {{questPercent('Main Quest',c.mainProgress)}}%</span><span>{{c.quest}} · {{questPercent(c.quest,c.sideProgress)}}%</span></small></button><button class="trash-button" [attr.aria-label]="'Delete '+c.name" [title]="'Delete '+c.name" (click)="confirmDelete(c,$event)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 10v7M14 10v7"/></svg></button></article>}@empty{<div class="panel empty"><h2>No stories here yet.</h2><p>Forge your first character, or clear your filters.</p></div>}</section>
@if(selected();as c){<div class="selected-character"><div class="character-preview has-character saved-character-preview" matchPortraitHeight><section class="panel sheet"><div class="sheet-content"><ng-container [ngTemplateOutlet]="characterSheet" [ngTemplateOutletContext]="{$implicit:c}"></ng-container><p class="hint record-summary">{{c.status}} · {{c.hours}} hours survived</p></div></section><div class="portrait-panel"><app-portrait [character]="c" (variantChange)="portraitChanged(c,$event)"></app-portrait></div></div><section class="panel detail run-tracking"><h2>Journal</h2><div class="facts"><div><label for="run-status">Status</label><select id="run-status" [ngModel]="c.status" (ngModelChange)="c.status=$event; autoSave(c)" [disabled]="recordedStatus!=='Alive'"><option>Alive</option><option>Dead</option><option [disabled]="!c.mainComplete||!c.sideComplete">Won</option></select></div><div><label for="run-hours">Hours Survived</label><input id="run-hours" type="number" min="0" [ngModel]="c.hours" (ngModelChange)="c.hours=$event; autoSave(c)"></div></div><div class="quest-grid"><div class="quest-progression"><label for="main-progression">Main Quest Progression</label><select id="main-progression" [disabled]="recordedStatus==='Won'" [ngModel]="c.mainProgress" (ngModelChange)="c.mainProgress=$event; autoSave(c)">@for(q of progressOptions('Main Quest',c.mainProgress);track q.value){<option [value]="q.value">{{q.label}}</option>}</select><div class="completion-indicator" [class.complete]="c.mainComplete" role="status">{{questPercent('Main Quest',c.mainProgress)}}% Complete</div></div><div class="quest-progression"><label for="side-progression">{{c.quest}} Progression</label><select id="side-progression" [disabled]="recordedStatus==='Won'" [ngModel]="c.sideProgress" (ngModelChange)="c.sideProgress=$event; autoSave(c)"><option value="">Not started</option>@for(q of progressOptions(c.quest,c.sideProgress);track q.value){<option [value]="q.value">{{q.label}}</option>}</select><div class="completion-indicator" [class.complete]="c.sideComplete" role="status">{{questPercent(c.quest,c.sideProgress)}}% Complete</div></div></div>@if(c.status==='Dead'){<label for="death-cause">What Killed You?</label><input id="death-cause" placeholder="A clannfear, a fatal fall, an ambitious decision…" [ngModel]="c.killedBy" (ngModelChange)="c.killedBy=$event; autoSave(c)">}<label for="run-notes">Journal</label><textarea id="run-notes" rows="12" placeholder="Memorable moments from this life" [ngModel]="c.notes" (ngModelChange)="c.notes=$event; autoSave(c)"></textarea><p class="hint">{{c.challenge?'Challenge · '+c.allowance+' death-earned changes at creation.':''}} {{recordedStatus!=='Alive'?'This run has ended; its outcome is locked.':''}}</p></section></div>}
</div>}
@if(tab()==='Challenge rules'){<div class="eyebrow">ONE LIFE. ONE CHANCE.</div><h1>The challenge.</h1><p class="intro">Beat the Main Quest and your assigned questline. Live to tell the tale.</p><section class="panel rules">@for(r of rules;track r;let i=$index){<div><span>{{(i+1).toString().padStart(2,'0')}}</span><p>{{r}}</p></div>}</section>}
<dialog #deleteDialog class="delete-dialog" aria-labelledby="delete-question" (cancel)="cancelDelete()" (click)="$event.target===deleteDialog && cancelDelete()"><p id="delete-question">Are you sure you want to delete this character?</p><p class="delete-explanation">Deleting a dead character can affect the number of stat changes you are allowed when creating a new character.</p><div class="actions"><button class="keep-button" (click)="cancelDelete()">No</button><button class="delete-button" (click)="approveDelete()">Yes</button></div></dialog><footer>Oblivion Remastered: Random Character Generator <span>Fan-made. Unaffiliated with Bethesda. All records stay on your device.</span></footer></main></div>`})
class App {
@ViewChild('deleteDialog',{static:true}) deleteDialog!:ElementRef<HTMLDialogElement>;
private deleteAnchor:HTMLElement|null=null;
confirmDelete(c:Character,event:Event){this.deleteTarget.set(c);this.deleteAnchor=event.currentTarget as HTMLElement;const dialog=this.deleteDialog.nativeElement;dialog.showModal();const rect=this.deleteAnchor.getBoundingClientRect();const width=dialog.offsetWidth,height=dialog.offsetHeight;dialog.style.left=Math.max(12,Math.min(rect.right-width,window.innerWidth-width-12))+'px';dialog.style.top=Math.max(12,Math.min(rect.bottom+8,window.innerHeight-height-12))+'px';dialog.querySelector<HTMLButtonElement>('.keep-button')?.focus();}
cancelDelete(){this.deleteDialog.nativeElement.close();this.deleteTarget.set(null);this.deleteAnchor?.focus();}
approveDelete(){const c=this.deleteTarget();this.cancelDelete();if(c)this.remove(c);}
private ledgerRevision=signal(0);
nameLimit=NAME_LIMIT;limitName=limitName;
portraitChanged(c:Character,variant:'Male'|'Female'){c.portraitVariant=variant;if(this.selected()?.id===c.id)this.autoSave(c);}
portraitArmor=portraitArmor;portraitKey=portraitKey;portraitSource=portraitSource;
tabs=['Forge','Characters','Challenge rules'];tab=signal('Forge');modes=['Balanced Random','True Random'];mode=this.modes[0];challenge=true;data:Ledger={version:1,characters:[]};draft=signal<Character|null>(null);selected=signal<Character|null>(null);ready=signal(false);busy=signal(false);error=signal('');savePath='Browser local storage (desktop uses characters.json)';search='';filter='All';showSavePath=signal(false);recordedStatus='Alive';deleteTarget=signal<Character|null>(null);saveStatus=signal('All changes saved');private operationQueue:Promise<void>=Promise.resolve();private pendingEdits=new Map<string,Character>();private pendingSaves=0;editField='Birthsign';editValue='';
rules=['Play on Expert difficulty or higher. No fast travel.','Use only weapons, armor and spell schools covered by your seven major skills. Clothing is allowed.','Shields require Block; repair hammers require Armorer; lockpicking requires Security. Haggling requires Mercantile, and the persuasion wheel requires Speechcraft.','Scrolls and staves are allowed regardless of spell school.','Keep the game as close to vanilla as possible. Light mods are allowed; avoid changes that undermine the challenge.','Death ends the run. Start from the beginning with a newly randomized character.','Each saved dead character grants one optional change to the next character. Deleting a dead character removes that credit. Change a race, origin, birthsign, specialization, one attribute, or one skill before saving. Changing race also selects a valid origin.','Win by completing the Main Quest and the randomly assigned guild or DLC questline. Record both as completed to mark a victory.'];
constructor(){window.ledger?.onFlush?.(()=>this.operationQueue);void this.load();}
async load(){try{this.data=window.ledger?await window.ledger.load():JSON.parse(localStorage.getItem('fate-ledger')||'{"version":1,"characters":[]}');if(this.data.version!==1||!Array.isArray(this.data.characters))throw Error('Unsupported save format. Existing data has been preserved.');this.data.characters.forEach(migrateProgress);this.data=migrateChallenge(this.data);this.data.characters.forEach(c=>c.portraitVariant=c.portraitVariant==='Female'?'Female':'Male');if(window.ledger)this.savePath=await window.ledger.path();this.ready.set(true);}catch(e){this.error.set(String(e));}}
deaths(){this.ledgerRevision();return deathCount(this.data);}
questPercent=questPercent;
sorted(values:string[]){return [...values].sort((a,b)=>a.localeCompare(b));}
changeFields(c:Character){return [...['Race','Origin','Birthsign','Specialization'].map(value=>({value,label:value})),...this.sorted(c.attributes).map(value=>({value:'Attribute:'+value,label:value})),...this.sorted(c.skills).map(value=>({value:'Skill:'+value,label:value}))];}
skillColumns(c:Character){const ordered=[...c.skills].sort((a,b)=>a.localeCompare(b));return [ordered.slice(0,4),ordered.slice(4)];}
async roll(){await this.operationQueue;this.draft.set(generate(this.mode,this.challenge,this.challenge?deathCount(this.data):0));this.editValue='';this.editField='Birthsign';}
refreshDraftAllowance(){const c=this.draft();if(!c?.challenge)return;const allowance=deathCount(this.data);if(c.changes>allowance){this.draft.set(generate(c.mode,true,allowance));this.editField='Birthsign';this.editValue='';this.error.set('A deleted death reduced your available changes. Your unsaved character was rerolled to match the remaining credits.');}else this.draft.set({...c,allowance});}
async persist(next:Ledger){this.busy.set(true);this.error.set('');try{if(window.ledger)await window.ledger.save(next);else localStorage.setItem('fate-ledger',JSON.stringify(next));this.data=next;this.refreshDraftAllowance();this.ledgerRevision.update(n=>n+1);return true;}catch(e){this.error.set('Save failed: '+String(e));return false;}finally{this.busy.set(false);}}
async saveDraft(){await this.operationQueue;const c=this.draft();if(!c)return;c.started=true;const next=structuredClone(this.data);next.characters.unshift(structuredClone(c));if(await this.persist(next)){this.draft.set(null);this.select(c);this.tab.set('Characters');}}
filtered(){this.ledgerRevision();return this.data.characters.filter(c=>(this.filter==='All'||c.status===this.filter)&&(c.name+' '+c.race+' '+c.quest).toLowerCase().includes(this.search.toLowerCase()));}
select(c:Character){const latest=this.pendingEdits.get(c.id)||this.data.characters.find(x=>x.id===c.id)||c;this.selected.set(structuredClone(latest));this.recordedStatus=this.data.characters.find(x=>x.id===c.id)?.status||c.status;this.deleteTarget.set(null);}
nameChanged(c:Character){if(this.selected()?.id===c.id)this.autoSave(c);}
progressOptions(line:string,current:string){const list=questlines[line]||[];const stages=questStages(line);const options=list.map((q,i)=>({value:q,label:stages[i]+'. '+q}));if(current&&!list.includes(current))options.unshift({value:current,label:'Legacy milestone: '+current});return options;}
autoSave(c:Character){deriveCompletion(c);const snapshot=structuredClone(c);if(!Number.isFinite(snapshot.hours)||snapshot.hours<0)snapshot.hours=this.data.characters.find(x=>x.id===c.id)?.hours||0;this.pendingEdits.set(c.id,snapshot);this.pendingSaves++;this.saveStatus.set('Saving…');this.operationQueue=this.operationQueue.then(async()=>{try{const next=structuredClone(this.data);const old=next.characters.find(x=>x.id===snapshot.id);if(!old)return;if(old.status!=='Alive')snapshot.status=old.status;if(snapshot.status==='Won'&&(!snapshot.mainComplete||!snapshot.sideComplete)){snapshot.status=old.status;this.error.set('Complete both questlines before recording a victory.');}next.characters=next.characters.map(x=>x.id===snapshot.id?snapshot:x);if(await this.persist(next)){if(this.pendingEdits.get(snapshot.id)===snapshot){this.pendingEdits.delete(snapshot.id);if(this.selected()?.id===snapshot.id)this.selected()!.status=snapshot.status;}if(this.selected()?.id===snapshot.id){this.recordedStatus=snapshot.status;if(snapshot.status!=='Alive')this.selected()!.status=snapshot.status;}}else this.saveStatus.set('Could not save changes');}finally{this.pendingSaves--;if(!this.pendingSaves&&this.saveStatus()!=='Could not save changes')this.saveStatus.set('All changes saved');}}).catch(e=>{this.error.set('Save failed: '+String(e));this.saveStatus.set('Could not save changes');});}
remove(c:Character){this.operationQueue=this.operationQueue.then(async()=>{const next=structuredClone(this.data);next.characters=next.characters.filter(x=>x.id!==c.id);if(await this.persist(next)){this.pendingEdits.delete(c.id);if(this.selected()?.id===c.id)this.selected.set(null);this.deleteTarget.set(null);}}).catch(e=>this.error.set('Delete failed: '+String(e)));}

async backup(){await this.operationQueue;try{if(window.ledger){await window.ledger.export();return;}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(this.data,null,2)],{type:'application/json'}));a.download='characters-backup.json';a.click();URL.revokeObjectURL(a.href);}catch(e){this.error.set(String(e));}}
editOptions(c:Character):string[]{if(this.editField==='Race')return Object.keys(races);if(this.editField==='Origin')return races[c.race];if(this.editField==='Birthsign')return birthsigns;if(this.editField==='Specialization')return ['Combat','Magic','Stealth'];if(this.editField.startsWith('Attribute'))return attributes.filter(x=>!c.attributes.includes(x));return skills.filter(x=>!c.skills.includes(x));}
change(c:Character){if(c.started||c.changes>=c.allowance||!this.changeFields(c).some(f=>f.value===this.editField)||!this.editOptions(c).includes(this.editValue))return;const v=this.editValue;switch(this.editField){case 'Race':if(c.race===v)return;c.race=v;c.origin=races[v][0];break;case 'Origin':if(c.origin===v)return;c.origin=v;break;case 'Birthsign':if(c.birthsign===v)return;c.birthsign=v;break;case 'Specialization':if(c.specialization===v)return;c.specialization=v;break;default:if(this.editField.startsWith('Attribute'))c.attributes[c.attributes.indexOf(this.editField.slice(10))]=v;else c.skills[c.skills.indexOf(this.editField.slice(6))]=v;}c.changes++;this.editValue='';this.editField='Birthsign';}
}
bootstrapApplication(App).catch(console.error);



