export const races: Record<string,string[]> = {'Argonian':['Arnesia','Thornmarsh'],'Breton':['Systres','High Rock'],'Dark Elf':['Vvardenfell','Mainland'],'High Elf':['Auridon','Summerset'],'Imperial':['Nibenay','Colovia'],'Khajiit':['Anequina','Pellitine'],'Nord':['Western','Eastern'],'Orc':['Stronghold','Orsinium'],'Redguard':['Dragontail Mountains',"Alik'r Desert"],'Wood Elf':['Grahtwood',"Reaper's March"]};
export const birthsigns = ['Apprentice','Atronach','Lady','Lord','Lover','Mage','Ritual','Serpent','Shadow','Steed','Thief','Tower','Warrior'];
export const attributes = ['Agility','Endurance','Intelligence','Luck','Personality','Speed','Strength','Willpower'];
export const skills = ['Acrobatics','Alchemy','Alteration','Armorer','Athletics','Blade','Block','Blunt','Conjuration','Destruction','Hand to Hand','Heavy Armor','Illusion','Light Armor','Marksman','Mercantile','Mysticism','Restoration','Security','Sneak','Speechcraft'];
export const quests = ['Fighters Guild','Mages Guild','Thieves Guild','Dark Brotherhood','Knights of the Nine','Shivering Isles'];
export const melee = ['Blade','Blunt','Hand to Hand'];
export const damage = [...melee,'Marksman','Destruction','Conjuration','Restoration'];
export const utility = ['Acrobatics','Alchemy','Alteration','Armorer','Athletics','Illusion','Mercantile','Mysticism','Security','Sneak','Speechcraft'];
export interface Character {id:string; name:string; portraitVariant?:'Male'|'Female'; className:string; race:string; origin:string; birthsign:string; specialization:string; attributes:string[]; skills:string[]; quest:string; mode:string; challenge:boolean; allowance:number; changes:number; started:boolean; created:string; status:string; hours:number; mainProgress:string; sideProgress:string; mainComplete:boolean; sideComplete:boolean; killedBy:string; notes:string;}
export interface Ledger {version:1; characters:Character[];}
export function balanced(s:string[]) {return !(s.includes('Light Armor') && s.includes('Heavy Armor')) && s.filter(x=>melee.includes(x)).length<=1 && s.some(x=>damage.includes(x)) && s.filter(x=>utility.includes(x)).length>=2;}
export function pick<T>(a:T[],rng= Math.random):T {return a[Math.floor(rng()*a.length)];}
export function sample<T>(a:T[],n:number,rng=Math.random):T[] {const b=[...a]; for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b.slice(0,n);}
export function generate(mode:string,challenge:boolean,allowance:number):Character {let s:string[]; do {s=sample(skills,7);}while(mode==='Balanced Random'&&!balanced(s));const race=pick(Object.keys(races));return {id:crypto.randomUUID(),name:'New Character',portraitVariant:'Male',className:'Custom class',race,origin:pick(races[race]),birthsign:pick(birthsigns),specialization:pick(['Combat','Magic','Stealth']),attributes:sample(attributes,2),skills:s,quest:pick(quests),mode,challenge,allowance,changes:0,started:false,created:new Date().toISOString(),status:'Alive',hours:0,mainProgress:'Tutorial',sideProgress:'',mainComplete:false,sideComplete:false,killedBy:'',notes:''};}
